import { Resend } from "resend";
import { site, services } from "@/data/site";
import { getPrisma } from "@/lib/database/prisma";
import type { AppointmentRecord } from "@/types/appointment";
import { buildWhatsAppUrl, formatAppointmentMessage } from "./format";

type Channel = "EMAIL_ADMIN" | "EMAIL_CUSTOMER" | "WHATSAPP_META";
const cleanError = (error: unknown) => (error instanceof Error ? error.message : "échec inconnu").replace(/[\r\n]+/g, " ").slice(0, 300);
async function logAttempt(appointmentId:string,channel:Channel,success:boolean,providerId?:string,error?:unknown){const db=getPrisma();if(!db)return;await db.notificationLog.create({data:{appointmentId,channel,success,providerId,sanitizedError:error?cleanError(error):undefined}}).catch(()=>undefined);}

function emailContent(a:AppointmentRecord){const service=services.find(x=>x.id===a.serviceId);const customerWa=buildWhatsAppUrl(a.whatsapp,`Bonjour ${a.customerName}, au sujet de votre demande ${a.reference} chez Princesse Coiffure.`);const reply=a.email?`mailto:${encodeURIComponent(a.email)}?subject=${encodeURIComponent(`Rendez-vous ${a.reference}`)}`:"";return `${formatAppointmentMessage(a)}\nPrix indicatif : ${a.quotedPrice||service?.price||"À confirmer"}\nDurée : ${service?.duration||`${a.durationMinutes||"—"} minutes`}\n\nRépondre sur WhatsApp : ${customerWa}${reply?`\nRépondre par email : ${reply}`:""}`;}

export async function notifyPrincesse(a:AppointmentRecord){const errors:string[]=[];let emailSent=false,customerEmailSent=false,whatsappSent=false;const message=formatAppointmentMessage(a);const resendReady=Boolean(process.env.RESEND_API_KEY&&process.env.EMAIL_FROM&&process.env.PRINCESSE_EMAIL);
  if(resendReady){const resend=new Resend(process.env.RESEND_API_KEY);try{const result=await resend.emails.send({from:process.env.EMAIL_FROM!,to:process.env.PRINCESSE_EMAIL!,replyTo:a.email||process.env.EMAIL_REPLY_TO,subject:`Nouveau rendez-vous ${a.reference}`,text:emailContent(a)});if(result.error)throw new Error(result.error.message);emailSent=true;await logAttempt(a.id,"EMAIL_ADMIN",true,result.data?.id);}catch(error){errors.push(`Email: ${cleanError(error)}`);await logAttempt(a.id,"EMAIL_ADMIN",false,undefined,error)}
    if(a.email){try{const result=await resend.emails.send({from:process.env.EMAIL_FROM!,to:a.email,replyTo:process.env.EMAIL_REPLY_TO||process.env.PRINCESSE_EMAIL,subject:`Demande reçue — ${a.reference}`,text:`Bonjour ${a.customerName},\n\nVotre demande de rendez-vous du ${a.appointmentDate} à ${a.appointmentTime} a bien été reçue. Elle n'est pas encore confirmée par Princesse.\n\nRéférence : ${a.reference}\n\nPrincesse Coiffure`});if(result.error)throw new Error(result.error.message);customerEmailSent=true;await logAttempt(a.id,"EMAIL_CUSTOMER",true,result.data?.id);}catch(error){errors.push(`Confirmation cliente: ${cleanError(error)}`);await logAttempt(a.id,"EMAIL_CUSTOMER",false,undefined,error)}}}
  const metaReady=Boolean(process.env.WHATSAPP_PHONE_NUMBER_ID&&process.env.WHATSAPP_ACCESS_TOKEN&&process.env.WHATSAPP_BUSINESS_ACCOUNT_ID&&process.env.WHATSAPP_TEMPLATE_NAME&&process.env.PRINCESSE_WHATSAPP);
  if(metaReady){try{const response=await fetch(`https://graph.facebook.com/v23.0/${process.env.WHATSAPP_PHONE_NUMBER_ID}/messages`,{method:"POST",signal:AbortSignal.timeout(10_000),headers:{Authorization:`Bearer ${process.env.WHATSAPP_ACCESS_TOKEN}`,"Content-Type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",to:process.env.PRINCESSE_WHATSAPP!.replace(/\D/g,""),type:"template",template:{name:process.env.WHATSAPP_TEMPLATE_NAME,language:{code:"fr"},components:[{type:"body",parameters:[{type:"text",text:message}]}]}})});if(!response.ok)throw new Error(`Meta HTTP ${response.status}`);const payload=await response.json() as {messages?:Array<{id?:string}>};whatsappSent=true;await logAttempt(a.id,"WHATSAPP_META",true,payload.messages?.[0]?.id);}catch(error){errors.push(`WhatsApp: ${cleanError(error)}`);await logAttempt(a.id,"WHATSAPP_META",false,undefined,error)}}
  return{emailSent,customerEmailSent,whatsappSent,errors,whatsappUrl:buildWhatsAppUrl(site.whatsapp,message)};}
