import Link from "next/link";
import { hairstyles, services, site } from "@/data/site";
import { ShowcaseLoader } from "@/components/three/showcase-loader";

export default function Home(){return <>
  <section className="overflow-hidden bg-[radial-gradient(circle_at_75%_30%,#ecd3c8,transparent_38%)]"><div className="mx-auto grid min-h-[72vh] max-w-6xl items-center gap-10 px-5 py-20 md:grid-cols-2"><div><p className="mb-4 text-xs uppercase tracking-[.3em] text-[#9a624d]">Beauté • précision • confiance</p><h1 className="font-serif text-5xl leading-[.95] md:text-7xl">Votre coiffure,<br/><em className="text-[#a86f43]">votre couronne.</em></h1><p className="mt-6 max-w-lg text-base leading-7 text-black/65">Princesse vous accueille pour une expérience personnalisée et des finitions qui vous ressemblent.</p><div className="mt-8 flex flex-wrap gap-3"><Link className="rounded-full bg-[#231b1b] px-6 py-3 text-white" href="/rendez-vous">Prendre rendez-vous</Link><Link className="rounded-full border border-black/20 px-6 py-3" href="/coiffures">Voir les modèles</Link></div></div><div className="relative mx-auto aspect-[4/5] w-full max-w-sm rounded-[10rem_10rem_2rem_2rem] bg-gradient-to-b from-[#d8ad9d] to-[#825a4a] shadow-2xl"><span className="absolute inset-0 grid place-items-center px-10 text-center text-sm text-white/75">Photo professionnelle de Princesse à ajouter</span></div></div></section>
  <section className="mx-auto max-w-6xl px-5 py-20"><p className="text-xs uppercase tracking-[.25em] text-[#9a624d]">Sélection</p><h2 className="mt-2 font-serif text-4xl">Coiffures populaires</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{hairstyles.map(x=><article key={x.id} className="rounded-3xl bg-[#f2dfd7] p-7"><div className="aspect-[4/3] rounded-2xl bg-[#d8ad9d]"/><p className="mt-5 text-xs uppercase tracking-widest">{x.category}</p><h3 className="font-serif text-2xl">{x.name}</h3><Link className="mt-4 inline-block text-sm underline" href={`/rendez-vous?coiffure=${x.id}`}>Choisir ce modèle</Link></article>)}</div></section>
  <section className="bg-white"><div className="mx-auto max-w-6xl px-5 py-20"><h2 className="font-serif text-4xl">Des services pensés pour vous</h2><div className="mt-8 grid gap-5 md:grid-cols-3">{services.map(x=><article key={x.id} className="rounded-3xl border border-black/10 p-7"><h3 className="font-serif text-2xl">{x.name}</h3><p className="mt-3 text-sm leading-6 text-black/60">{x.description}</p><p className="mt-5 text-sm">{x.duration} · {x.price}</p></article>)}</div></div></section>
  <section className="mx-auto grid max-w-6xl items-center gap-10 px-5 py-20 md:grid-cols-2"><div><p className="text-xs uppercase tracking-[.25em] text-[#9a624d]">Vue immersive</p><h2 className="mt-3 font-serif text-4xl">Une coiffure sous tous ses angles</h2><p className="mt-5 leading-7 text-black/60">Cette démonstration légère prépare l’emplacement du futur modèle officiel. Elle se charge côté client et respecte la réduction des mouvements.</p></div><ShowcaseLoader/></section>
  <section className="mx-auto max-w-4xl px-5 py-20 text-center"><p className="text-xs uppercase tracking-[.25em]">Le rendez-vous</p><h2 className="mt-3 font-serif text-4xl">Choisissez. Réservez. Rayonnez.</h2><p className="mx-auto mt-5 max-w-2xl text-black/60">Sélectionnez votre prestation et votre créneau. Princesse reçoit votre demande et vous recontacte pour la confirmer.</p><Link className="mt-8 inline-block rounded-full bg-[#a86f43] px-7 py-3 text-white" href="/rendez-vous">Commencer</Link></section>
  <section className="bg-white"><div className="mx-auto max-w-6xl px-5 py-20"><p className="text-xs uppercase tracking-[.25em] text-[#9a624d]">Témoignages</p><h2 className="mt-3 font-serif text-4xl">La parole aux clientes</h2><div className="mt-8 grid gap-5 md:grid-cols-2">{["[TÉMOIGNAGE TEMPORAIRE] Une expérience à remplacer par l’avis authentique d’une cliente.","[TÉMOIGNAGE TEMPORAIRE] Ce contenu sera publié après accord de la cliente."].map((quote,i)=><blockquote key={i} className="rounded-3xl bg-[#fffaf6] p-7 text-black/65">“{quote}”<footer className="mt-4 text-xs uppercase tracking-widest">Cliente — nom à confirmer</footer></blockquote>)}</div></div></section>
  <section className="bg-[#ead8cf]"><div className="mx-auto max-w-6xl px-5 py-14"><h2 className="font-serif text-3xl">Nous trouver</h2><p className="mt-3">{site.address} · {site.hours}</p><p className="mt-2 text-sm text-black/55">Coordonnées temporaires à remplacer avant mise en ligne.</p></div></section>
</>}
